### PR TITLE
Add changelog links

### PR DESCRIPTION
**Pull request by LastTalon**
This improves documentation slightly by implementing links to releases for each version in the changelog.

Some of the versions link to other notes because they were released with their notes on a subsequent release.

### CODE REVIEW

**Comment by Kampfkarren** [comment]
Can you have the links for these be in the headers themselves? After that, I might have to adjust the shell script for extracting changelogs.

**Comment by LastTalon** [comment]
Sure, I can do that. Typically I would recommend grouping them, since updating them and changing them is easier with them together.

Is there something the script does that it should be in the headers?

**Comment by Kampfkarren** [comment]
The script is here: https://github.com/Kampfkarren/selene/blob/main/misc/extract-changelog.sh

I think right now it just uses the most recent header, so should be okay.

**Comment by LastTalon** [comment]
It appears to do the same thing after the changes. You may want to check yourself, since I'm unsure exactly what its supposed to look like.

**Pull request merged**
