### PR TITLE
Add string.split to roblox std

### PR DESCRIPTION
**Pull request by evaera**
Second param is actually optional but idk how to denote that

### CODE REVIEW

**Comment by Kampfkarren** [comment]
Yeah this isn't right. This means that the only acceptable usage will be `string.split("string")` (and no other value). Take a look at the docs for the standard library or the built in ones for an example of how it should look.

**Comment by evaera** [comment]
Just fix it yourself loser

**Comment by Kampfkarren** [comment]
Looks good! Can you quickly update the CHANGELOG and I can merge this in? :)

**Comment by Kampfkarren** [comment]
Perfect!

**Pull request merged**
