### PR TITLE
chore: use "rule" instead of "lint"

### LINKED ISSUE #48: Replace "rules" with "lints"
Seen both in the source code and the config option. Can deprecate the `rules` config entry but keep it around.

### PR DESCRIPTION
**Pull request by sno2**
Closes #48 

Gotta catch 'em all.

### CODE REVIEW

**Comment by sno2** [comment]
Forgot to make the CLI option backwards-compatible, doing that rn

**Comment by sno2** [comment]
Alright, now it's ready for review. Thanks

**Comment by Kampfkarren** [comment]
Nice! Two comments:

1. You should rename RULE_TYPE to LINT_TYPE
2. Some of these changed line endings. My money is that they're being correctly formatted to LF, but I would like if you kept whatever line endings they had before just for sake of review

**Comment by sno2** [comment]
Hmm I've tried both CRLF and LF for `selene-lib/src/lints/unused_variable.rs` and `selene-lib/src/lints/ifs_same_cond.rs` but the diff is not shrinking like others. I am not sure what is going on there.

**Comment by sno2** [comment]
Can you try pasting the code into an online diff checker to make sure I haven't messed with anything else? (https://diffonline.net/ is one)

**Comment by Kampfkarren** [comment]
I would try pulling in the fresh main versions, commit those unchanged, make your replacements, `git diff` beforehand to make sure it's just the rules -> lint changes, and then push.

Also, can you put in the CHANGELOG.md in "Changed" that "rules" in selene.toml should now be "lints", though both are compatible? Eventually we can make this a warning but the infrastructure isn't *quite* there yet.

**Comment by sno2** [comment]
Superseded by #444 . Sorry, couldn't figure out how to get the branches to work together.

**Pull request closed without merging**
