### PR TITLE
Add `utf8` globals to `lua53` std

### LINKED ISSUE #385: Add `utf8` globals to `lua53.yaml`
Lua 5.3 has the [`utf8` global](https://q-syshelp.qsc.com/Content/Control_Scripting/Lua_5.3_Reference_Manual/Standard_Libraries/4_-_Basic_UTF-8_Support.htm) which provides basic support for utf-8 encoding. This seems to be missing from selene's standard library file for the version.

I'm willing to make a PR for this if needed.

### PR DESCRIPTION
**Pull request by ProspectPyxis**
Closes #385.

### CODE REVIEW

**Comment by Kampfkarren** [comment]
Update the CHANGELOG.md as well--make a new section called Unreleased. Then, this is good.

**Comment by ProspectPyxis** [comment]
Done!

**Comment by Kampfkarren** [comment]
Thanks! Will merge if tests pass. Do you need an update soon after merge?

**Comment by ProspectPyxis** [comment]
No, it's not urgent - just a nice quality of life feature. No need to rush an update.

**Comment by Kampfkarren** [comment]
Thanks!

**Pull request merged**
